### ISSUE TITLE
Get absolute file paths

### ISSUE THREAD

**Issue by RdeWilde** [absalomedia/sassphp#13]
**Is your feature request related to a problem? Please describe.**
Checking wether source files have been changed, to decide if we can used the cached file.

**Describe the solution you'd like**
An absolute reference to the path for all compiled files

**Describe alternatives you've considered**
Currently we get the relative path.

**Additional context**
In the source it seems to be an object with both data, relative and absolute.

I used the importer to register the parsed files:

```
// ....
	protected $parsedFiles = [];

	public function __construct() {
		parent::__construct();

		$this->setImporter([$this, 'import']);
	}

///...

	/*
	 * imp_path
	 * abs_path
	 * source
	 * srcmap
	 */
	public function import($arg) {
		// FIXME absolute import path
		if (!in_array($arg, $this->parsedFiles)) {
			$this->parsedFiles[] = $arg;
		}
	}
```
https://github.com/absalomedia/sassphp/blob/f7fb87e9cf6a4c8c0ab3ebaf82421e5b4aee388b/src/sass.c#L189

**Comment by absalomedia** [comment]
This should be rectified by the 0.7 release
