### ISSUE TITLE
Make a composer package that will compile and use the extension

### ISSUE THREAD

**Issue by abcarroll** [absalomedia/sassphp#2]
If you look at things such as node-sass, they work in much the same way php extensions do, by creating bindings to libsass within the v8 engine.

I will offer to create the pull request if you'd accept it, to make composer hooks to compile and load your bindings for php.  We don't have `dl()` anymore but I believe I could put something usable together.

**Comment by absalomedia** [comment]
By all means, go ahead

**Comment by zioth** [comment]
I'd be interested too. I had to hack it with a script.

**Comment by absalomedia** [comment]
Hey @zioth I'm more than a little rusty with how to encapsulate a Zend extension inside a Composer phar. Would you be able to share what you did?

**Comment by zioth** [comment]
I didn't do anything so sophisticated. I just wrote an install script that followed the instructions in your readme, and added this to my project's composer.json:

`
 "scripts": {
    "post-install-cmd": [
      "sh scripts/install_libsass.sh"
    ],
`

The install script looks like this:
```
#!/bin/sh

echo Installing sassphp...
cd vendor
if [ ! -d sassphp ]; then
    git clone git://github.com/absalomedia/sassphp
fi
cd sassphp
if [ `git rev-parse --short HEAD` != "4769678" ]; then
    git pull
    git reset --hard 4769678
    git submodule init
    git submodule update
    php install.php
    make install
    echo Sassphp successfully installed. Remember to add extension=sass.so to your php.ini. Actual path may be different. Use: sudo find / -name sass.so | grep -v sassphp
else
    echo Sassphp already up to date
fi
```

**Comment by absalomedia** [comment]
Composer package now integrated onto Packagist
