### ISSUE TITLE
Importer & function bindings

### ISSUE THREAD

**Issue by abcarroll** [absalomedia/sassphp#3]
Also, while I'm at it, is there any work that you're aware of to make decent bindings for the function & importer APIs on libsass?  I sorely need them -- I am quite rusty in c/c++, but may attempt it next week assuming it doesn't already exist as far as you know.

**Comment by absalomedia** [comment]
I'm still yet to get to the function & importer APIs. It's on the radar for things to do as the current build only focusses on using the compiler itself & the context.

There isn't any work on it as far as I know of.

**Comment by absalomedia** [comment]
May be fixed by #11 & associated work

**Comment by absalomedia** [comment]
Released in 0.7 release
