### ISSUE TITLE
PHP Stub for IDE codeintel/autocomplete

### ISSUE THREAD

**Issue by stephenreay** [absalomedia/sassphp#4]
A number of IDE's today can use 'stub' PHP files to facilitate auto-complete of class/constant/method/property names. These files are essentially just skeleton php files with methods/functions that have a matching signature but no body, and *usually* a phpdoc block e.g.:

	/**
	 * @param string $filename
	 *
	 * @return string|string[]
	 *
	 * @throws SassException
	 */
	public function compileFile ($filename) {}

I have created what I believe is an accurate stub file for the Sass extension, but without detailed docs beyond the readme, it's hard to be sure. I'm happy to add my existing stub file to the project, if someone could confirm/fix any parts that need it?

**Comment by absalomedia** [comment]
Would a PHP Storm stub do? I may be able to get one into the next release?

**Comment by stephenreay** [comment]
Absolutely, if you have a stub that PhpStorm works with, I think most other IDE's should be able to use it too.
