### ISSUE TITLE
Allow multiple include paths

### ISSUE THREAD

**Issue by zioth** [absalomedia/sassphp#6]
As best I can tell, setIncludePath() only allows you to set a single path. In my project, there are three. Both the node and java implementations of libsass allow multiple paths, so it should be possible.

If there's some way to do it, a documentation update would be useful. I tried multiple params, an array, and separating paths with commas, spaces and pipes, in the hope that I'd stumble on something. :)

**Comment by techmunk** [comment]
Try separating with a full colon ":".

**Comment by techmunk** [comment]
This is what I've been using and it seems to work. $include_paths is an array.
`$sass->setIncludePath(implode(':', array_reverse($include_paths)));`

**Comment by zioth** [comment]
That worked. Thanks! A documentation update would be useful, so no one else gets confused.

**Comment by techmunk** [comment]
Yeah, I think I found it burried somewhere in the libsass documentation. I think it was also a semi-colon on windows instead of full colon...

**Comment by techmunk** [comment]
Yeah, here! http://sass-lang.com/documentation/Sass.html#load_paths-class_method

> If the `SASS_PATH` environment variable is set, the initial value of `load_paths` will be initialized based on that. The variable should be a colon-separated list of path names (semicolon-separated on Windows).

**Comment by absalomedia** [comment]
I can investigate ways of sending PHP arrays across to the IncludePath so you don't have to resort to convoluted hacks, but it will take some time.

**Comment by absalomedia** [comment]
This may be fixed by my work on #11 once I've finished the sideport

**Comment by absalomedia** [comment]
Should be inside 0.7 release
