### ISSUE TITLE
Binary install documentation

### ISSUE THREAD

**Issue by slarti-b** [absalomedia/sassphp#7]
Any chance of getting a short documentation of what files actually need to be installed to do a binary installation (i.e. if I build locally and want to copy it out to the production machines).  is it just  /usr/lib64/php/modules/sass.so or are there libsass files that also need to be included?

(Sorry, I know I should be able to work this out myself but I don't speak Makefile so want to check)

**Comment by absalomedia** [comment]
I haven't needed to consider a binary deployment of the final shared module.  There may be some dependencies based on the LibSass library, but I will need time to investigate it to make sure.

**Comment by slarti-b** [comment]
Thanks.  I don't really want to have to install all the dev tools and PHP headers on the production servers just to get the library there...

**Comment by absalomedia** [comment]
I should have an answer for you by the 24th. Booked up till then unfortunately

**Comment by slarti-b** [comment]
@absalomedia: That'd be great!  Thanks

**Comment by absalomedia** [comment]
@slarti-b I've done binary install documentation for you. You can copy the binary shared object (sass.so) from your development to production environments.

**Comment by slarti-b** [comment]
@absalomedia: Excellent.  Many thanks!  Will give it a go.
