### ISSUE TITLE
Ability to set variables outside of compile

### ISSUE THREAD

**Issue by jljr222** [absalomedia/sassphp#8]
I am creating an application that compiles custom theme settings into a CSS file. I would like to be able to set the variables via a command like setVariables that takes an array of sass variables. Not sure if there is a current workaround for this, but I would like to overrite the default sass variables I've set.

In addition, is there a way to compile the .scss files directly to a css file? I didn't see a command to do that.

**Comment by rodrigoaguilera** [comment]
I am doing a similar thing for Drupal themes. You can write a file that "@import" the sass you want to compile plus another with the variables you want to override. The advantage of this workaround is that you can control the order in case the variables have !default.
I find this addition quite valuable.

As for the second paragraph I don't think a PHP extension should concern with writing files but if you think is needed I feel you should open a different issue to discuss there. It nothing to do with the first.

**Comment by absalomedia** [comment]
> In addition, is there a way to compile the .scss files directly to a css file? I didn't see a command to do that.

the compileFile function compilies a single SCSS file to CSS. The output can be written as a CSS file anywhere you need it.

I'm still investigating the best path to implement LibSass' variable functions so those who use SassPHP can override & set them to suit.

**Comment by jljr222** [comment]
> I am doing a similar thing for Drupal themes. You can write a file that "@import" the sass you want to compile plus another with the variables you want to override. The advantage of this workaround is that you can control the order in case the variables have !default.
> I find this addition quite valuable.
> 
> As for the second paragraph I don't think a PHP extension should concern with writing files but if you think is needed I feel you should open a different issue to discuss there. It nothing to do with the first.

Could you provide an example of this? I just want to make sure I understand :)

> > In addition, is there a way to compile the .scss files directly to a css file? I didn't see a command to do that.
> 
> the compileFile function compilies a single SCSS file to CSS. The output can be written as a CSS file anywhere you need it.
> 
> I'm still investigating the best path to implement LibSass' variable functions so those who use SassPHP can override & set them to suit.

That would be awesome. So I could compile the SCSS from into css and place the contents into a CSS file using file_put_contents, correct?

**Comment by rodrigoaguilera** [comment]
I have this code:

```
                foreach ($customOptions as $variableName => $variableValue) {
                  $sourceImports .= $variableName . ": " . $variableValue . ";\n";
                }
                $sourceImports .= "@import \"" . $source . "\";\n";

                
```
and later
```
            $sass = new \Sass();
            $sass->setStyle(\Sass::STYLE_COMPRESSED);
            $css = $sass->compile($sourceImports);
```

Does this make it more clear?

**Comment by jljr222** [comment]
Very helpful, thank you so much!
